import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/app/globals.css";
import { TRPCProvider } from "@/trpc/client";
import { SidebarProvider } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";
import { Toaster } from "@/components/ui/sonner";
import { Header } from "@/components/layout/header";
import { getServerSession, getServerWorkspaces } from "@/lib/auth";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const data = await getServerSession();
  const workspaces = await getServerWorkspaces();
  return (
    <html lang='en' className={`${inter.variable} h-full antialiased`}>
      <body>
        <TRPCProvider>
          <SidebarProvider>
            <AppSidebar workspaces={workspaces} />
            <main className='flex flex-col w-full gap-6'>
              <Header user={data?.user || null} />
              {children}
            </main>
            <Toaster richColors />
          </SidebarProvider>
        </TRPCProvider>
      </body>
    </html>
  );
}
